apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployphp
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: myphppod
      labels:
        env: production
      spec:
        containers:
        - name: myphp
          image: souvikdutta7012/mykubephp:v1